### PR TITLE
Sort particles by order before writing

### PR DESCRIPTION
**Pull request by AjayMT**
This addresses issue #16 by gathering particles in a single Writer chare and sorting particles by order before writing output.

### CODE REVIEW

**Comment by minitu** [comment]
LGTM, but sometime in the future we should change `Writer` to be a chare group and use parallel sorting so that it's scalable.
For now I think this is fine since it's only used for testing correctness.

**Comment by trquinn** [comment]
> LGTM, but sometime in the future we should change `Writer` to be a chare group and use parallel sorting so that it's scalable.
> For now I think this is fine since it's only used for testing correctness.

The parallel part of the sort can be done trivially via a "radix sort".

**Comment by minitu** [comment]
@trquinn Could you elaborate on that? Do you mean something like TPs dividing the entire particle key range by `num_writers` and sending the particles that belong to each portion to the owner `Writer`, then the `Writer`s performing a local sort?

**Comment by trquinn** [comment]
The "keys" in this case are the "order" number, which we know run from 0 to n_particles.  Therefore each writer chare takes particles with order from index*(nparts/nwriters) to (index+1)*(nparts/nwriters).  Then, as you say, the Writers do a local sort.

**Pull request merged**
